import type { ScopeSpec } from "@/types";

export const ATHLON_SCOPES: ScopeSpec[] = [
  {
    id: "athlon-argos-btr-gen2-1-8x24",
    brand: "Athlon",
    model: "Argos BTR Gen2 1-8x24",
    fullName: "Athlon Argos BTR Gen2 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "athlon-argos-btr-gen2-6-24x50",
    brand: "Athlon",
    model: "Argos BTR Gen2 6-24x50",
    fullName: "Athlon Argos BTR Gen2 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "athlon-ares-etr-4-5-30x56",
    brand: "Athlon",
    model: "Ares ETR 4.5-30x56",
    fullName: "Athlon Ares ETR 4.5-30x56",
    tubeDiameter: "34mm",
    overallLength: 14.6,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1500,
  },
  {
    id: "athlon-cronus-btr-gen2-4-5-29x56",
    brand: "Athlon",
    model: "Cronus BTR Gen2 4.5-29x56",
    fullName: "Athlon Cronus BTR Gen2 4.5-29x56",
    tubeDiameter: "34mm",
    overallLength: 14.2,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2000,
  },
  {
    id: "athlon-helos-btr-gen2-6-24x56",
    brand: "Athlon",
    model: "Helos BTR Gen2 6-24x56",
    fullName: "Athlon Helos BTR Gen2 6-24x56",
    tubeDiameter: "34mm",
    overallLength: 14.3,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 700,
  },
  {
    id: "athlon-midas-tac-4-16x44",
    brand: "Athlon",
    model: "Midas TAC 4-16x44",
    fullName: "Athlon Midas TAC 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "athlon-midas-tac-6-24x50",
    brand: "Athlon",
    model: "Midas TAC 6-24x50",
    fullName: "Athlon Midas TAC 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 600,
  },
  {
    id: "athlon-ares-btr-gen2-2-5-15x50",
    brand: "Athlon",
    model: "Ares BTR Gen2 2.5-15x50",
    fullName: "Athlon Ares BTR Gen2 2.5-15x50",
    tubeDiameter: "34mm",
    overallLength: 13.8,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 800,
  },
  {
    id: "athlon-cronus-btr-gen2-1-6x24",
    brand: "Athlon",
    model: "Cronus BTR Gen2 1-6x24",
    fullName: "Athlon Cronus BTR Gen2 1-6x24",
    tubeDiameter: "34mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1500,
  },
  {
    id: "athlon-talos-btr-1-4x24",
    brand: "Athlon",
    model: "Talos BTR 1-4x24",
    fullName: "Athlon Talos BTR 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 200,
  },
];
