import type { ScopeSpec } from "@/types";

export const BURRIS_SCOPES: ScopeSpec[] = [
  {
    id: "burris-xtr2-1-5x24",
    brand: "Burris",
    model: "XTR II 1-5x24",
    fullName: "Burris XTR II 1-5x24",
    tubeDiameter: "34mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 700,
  },
  {
    id: "burris-xtr2-2-10x42",
    brand: "Burris",
    model: "XTR II 2-10x42",
    fullName: "Burris XTR II 2-10x42",
    tubeDiameter: "34mm",
    overallLength: 13.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "burris-xtr2-3-15x50",
    brand: "Burris",
    model: "XTR II 3-15x50",
    fullName: "Burris XTR II 3-15x50",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 900,
  },
  {
    id: "burris-xtr2-4-20x50",
    brand: "Burris",
    model: "XTR II 4-20x50",
    fullName: "Burris XTR II 4-20x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },
  {
    id: "burris-xtr2-5-25x50",
    brand: "Burris",
    model: "XTR II 5-25x50",
    fullName: "Burris XTR II 5-25x50",
    tubeDiameter: "34mm",
    overallLength: 14.75,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1100,
  },
  {
    id: "burris-xtr3-3-3-18x50",
    brand: "Burris",
    model: "XTR III 3.3-18x50",
    fullName: "Burris XTR III 3.3-18x50",
    tubeDiameter: "34mm",
    overallLength: 13.7,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1700,
  },
  {
    id: "burris-xtr3-5-5-30x56",
    brand: "Burris",
    model: "XTR III 5.5-30x56",
    fullName: "Burris XTR III 5.5-30x56",
    tubeDiameter: "34mm",
    overallLength: 14.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1900,
  },
  {
    id: "burris-fullfield4-2-5-10x42",
    brand: "Burris",
    model: "Fullfield IV 2.5-10x42",
    fullName: "Burris Fullfield IV 2.5-10x42",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "burris-fullfield4-3-12x42",
    brand: "Burris",
    model: "Fullfield IV 3-12x42",
    fullName: "Burris Fullfield IV 3-12x42",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 450,
  },
  {
    id: "burris-fullfield4-4-16x50",
    brand: "Burris",
    model: "Fullfield IV 4-16x50",
    fullName: "Burris Fullfield IV 4-16x50",
    tubeDiameter: "1in",
    overallLength: 14.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "burris-fullfield4-6-24x50",
    brand: "Burris",
    model: "Fullfield IV 6-24x50",
    fullName: "Burris Fullfield IV 6-24x50",
    tubeDiameter: "1in",
    overallLength: 15.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 550,
  },
  {
    id: "burris-veracity-ph-2-5-12x42",
    brand: "Burris",
    model: "Veracity PH 2.5-12x42",
    fullName: "Burris Veracity PH 2.5-12x42",
    tubeDiameter: "30mm",
    overallLength: 12.8,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "burris-veracity-ph-4-20x50",
    brand: "Burris",
    model: "Veracity PH 4-20x50",
    fullName: "Burris Veracity PH 4-20x50",
    tubeDiameter: "30mm",
    overallLength: 14.2,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 800,
  },
  {
    id: "burris-rt6-1-6x24",
    brand: "Burris",
    model: "RT-6 1-6x24",
    fullName: "Burris RT-6 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
];
