import type { ScopeSpec } from "@/types";

export const BUSHNELL_SCOPES: ScopeSpec[] = [
  {
    id: "bushnell-elite-tactical-xrs2-4-5-30x50",
    brand: "Bushnell",
    model: "Elite Tactical XRS2 4.5-30x50",
    fullName: "Bushnell Elite Tactical XRS2 4.5-30x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1300,
  },
  {
    id: "bushnell-elite-tactical-xrs3-6-36x56",
    brand: "Bushnell",
    model: "Elite Tactical XRS3 6-36x56",
    fullName: "Bushnell Elite Tactical XRS3 6-36x56",
    tubeDiameter: "34mm",
    overallLength: 15.5,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2000,
  },
  {
    id: "bushnell-match-pro-6-24x50",
    brand: "Bushnell",
    model: "Match Pro 6-24x50",
    fullName: "Bushnell Match Pro 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "bushnell-engage-2-5-10x44",
    brand: "Bushnell",
    model: "Engage 2.5-10x44",
    fullName: "Bushnell Engage 2.5-10x44",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 250,
  },
  {
    id: "bushnell-engage-4-16x44",
    brand: "Bushnell",
    model: "Engage 4-16x44",
    fullName: "Bushnell Engage 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 300,
  },
  {
    id: "bushnell-engage-6-24x50",
    brand: "Bushnell",
    model: "Engage 6-24x50",
    fullName: "Bushnell Engage 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 350,
  },
  {
    id: "bushnell-prime-1-4x24",
    brand: "Bushnell",
    model: "Prime 1-4x24",
    fullName: "Bushnell Prime 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.0,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 280,
  },
  {
    id: "bushnell-prime-3-9x40",
    brand: "Bushnell",
    model: "Prime 3-9x40",
    fullName: "Bushnell Prime 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.2,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 200,
  },
  {
    id: "bushnell-prime-3-12x40",
    brand: "Bushnell",
    model: "Prime 3-12x40",
    fullName: "Bushnell Prime 3-12x40",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 220,
  },
  {
    id: "bushnell-prime-6-18x50",
    brand: "Bushnell",
    model: "Prime 6-18x50",
    fullName: "Bushnell Prime 6-18x50",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 300,
  },
  {
    id: "bushnell-nitro-2-5-10x44",
    brand: "Bushnell",
    model: "Nitro 2.5-10x44",
    fullName: "Bushnell Nitro 2.5-10x44",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "bushnell-nitro-3-12x44",
    brand: "Bushnell",
    model: "Nitro 3-12x44",
    fullName: "Bushnell Nitro 3-12x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 550,
  },
  {
    id: "bushnell-nitro-5-20x44",
    brand: "Bushnell",
    model: "Nitro 5-20x44",
    fullName: "Bushnell Nitro 5-20x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 600,
  },
  {
    id: "bushnell-nitro-6-24x50",
    brand: "Bushnell",
    model: "Nitro 6-24x50",
    fullName: "Bushnell Nitro 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 650,
  },
  {
    id: "bushnell-banner2-3-9x40",
    brand: "Bushnell",
    model: "Banner 2 3-9x40",
    fullName: "Bushnell Banner 2 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 100,
  },
  {
    id: "bushnell-banner2-4-12x40",
    brand: "Bushnell",
    model: "Banner 2 4-12x40",
    fullName: "Bushnell Banner 2 4-12x40",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 120,
  },
];
