import type { ScopeSpec } from "@/types";

export const LEUPOLD_SCOPES: ScopeSpec[] = [
  // ============================================
  // Leupold Mark 5HD
  // ============================================
  {
    id: "leupold-mark5hd-1-6x24",
    brand: "Leupold",
    model: "Mark 5HD 1-6x24",
    fullName: "Leupold Mark 5HD 1-6x24",
    tubeDiameter: "35mm",
    overallLength: 10.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2200,
  },
  {
    id: "leupold-mark5hd-3.6-18x44",
    brand: "Leupold",
    model: "Mark 5HD 3.6-18x44",
    fullName: "Leupold Mark 5HD 3.6-18x44",
    tubeDiameter: "35mm",
    overallLength: 12.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 2500,
  },
  {
    id: "leupold-mark5hd-5-25x56",
    brand: "Leupold",
    model: "Mark 5HD 5-25x56",
    fullName: "Leupold Mark 5HD 5-25x56",
    tubeDiameter: "35mm",
    overallLength: 15.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2800,
  },
  {
    id: "leupold-mark5hd-7-35x56",
    brand: "Leupold",
    model: "Mark 5HD 7-35x56",
    fullName: "Leupold Mark 5HD 7-35x56",
    tubeDiameter: "35mm",
    overallLength: 15.67,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3100,
  },

  // ============================================
  // Leupold Mark 4HD (NEW)
  // ============================================
  {
    id: "leupold-mark4hd-2.5-10x42",
    brand: "Leupold",
    model: "Mark 4HD 2.5-10x42",
    fullName: "Leupold Mark 4HD 2.5-10x42",
    tubeDiameter: "30mm",
    overallLength: 12.1,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1800,
  },
  {
    id: "leupold-mark4hd-4.5-18x52",
    brand: "Leupold",
    model: "Mark 4HD 4.5-18x52",
    fullName: "Leupold Mark 4HD 4.5-18x52",
    tubeDiameter: "30mm",
    overallLength: 13.6,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 2100,
  },
  {
    id: "leupold-mark4hd-6-24x52",
    brand: "Leupold",
    model: "Mark 4HD 6-24x52",
    fullName: "Leupold Mark 4HD 6-24x52",
    tubeDiameter: "30mm",
    overallLength: 14.6,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 2300,
  },

  // ============================================
  // Leupold VX-6HD (NEW)
  // ============================================
  {
    id: "leupold-vx6hd-1-6x24",
    brand: "Leupold",
    model: "VX-6HD 1-6x24",
    fullName: "Leupold VX-6HD 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1400,
  },
  {
    id: "leupold-vx6hd-2-12x42",
    brand: "Leupold",
    model: "VX-6HD 2-12x42",
    fullName: "Leupold VX-6HD 2-12x42",
    tubeDiameter: "30mm",
    overallLength: 12.6,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1600,
  },
  {
    id: "leupold-vx6hd-3-18x44",
    brand: "Leupold",
    model: "VX-6HD 3-18x44",
    fullName: "Leupold VX-6HD 3-18x44",
    tubeDiameter: "30mm",
    overallLength: 13.2,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1700,
  },
  {
    id: "leupold-vx6hd-3-18x50",
    brand: "Leupold",
    model: "VX-6HD 3-18x50",
    fullName: "Leupold VX-6HD 3-18x50",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1800,
  },
  {
    id: "leupold-vx6hd-4-24x52",
    brand: "Leupold",
    model: "VX-6HD 4-24x52",
    fullName: "Leupold VX-6HD 4-24x52",
    tubeDiameter: "30mm",
    overallLength: 14.3,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 2000,
  },

  // ============================================
  // Leupold VX-5HD
  // ============================================
  {
    id: "leupold-vx5hd-1-5x24",
    brand: "Leupold",
    model: "VX-5HD 1-5x24",
    fullName: "Leupold VX-5HD 1-5x24",
    tubeDiameter: "30mm",
    overallLength: 9.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1100,
  },
  {
    id: "leupold-vx5hd-2-10x42",
    brand: "Leupold",
    model: "VX-5HD 2-10x42",
    fullName: "Leupold VX-5HD 2-10x42",
    tubeDiameter: "30mm",
    overallLength: 12.4,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1200,
  },
  {
    id: "leupold-vx5hd-3-15x44",
    brand: "Leupold",
    model: "VX-5HD 3-15x44",
    fullName: "Leupold VX-5HD 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.1,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1300,
  },
  {
    id: "leupold-vx5hd-3-15x56",
    brand: "Leupold",
    model: "VX-5HD 3-15x56",
    fullName: "Leupold VX-5HD 3-15x56",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1500,
  },
  {
    id: "leupold-vx5hd-4-20x52",
    brand: "Leupold",
    model: "VX-5HD 4-20x52",
    fullName: "Leupold VX-5HD 4-20x52",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 1700,
  },

  // ============================================
  // Leupold VX-3i
  // ============================================
  {
    id: "leupold-vx3i-1.5-5x20",
    brand: "Leupold",
    model: "VX-3i 1.5-5x20",
    fullName: "Leupold VX-3i 1.5-5x20",
    tubeDiameter: "1in",
    overallLength: 9.3,
    objectiveDiameter: 20,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "leupold-vx3i-2.5-8x36",
    brand: "Leupold",
    model: "VX-3i 2.5-8x36",
    fullName: "Leupold VX-3i 2.5-8x36",
    tubeDiameter: "1in",
    overallLength: 11.3,
    objectiveDiameter: 36,
    suggestedHeight: "medium",
    msrp: 650,
  },
  {
    id: "leupold-vx3i-3.5-10x40",
    brand: "Leupold",
    model: "VX-3i 3.5-10x40",
    fullName: "Leupold VX-3i 3.5-10x40",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "leupold-vx3i-3.5-10x50",
    brand: "Leupold",
    model: "VX-3i 3.5-10x50",
    fullName: "Leupold VX-3i 3.5-10x50",
    tubeDiameter: "1in",
    overallLength: 12.8,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 800,
  },
  {
    id: "leupold-vx3i-4.5-14x40",
    brand: "Leupold",
    model: "VX-3i 4.5-14x40",
    fullName: "Leupold VX-3i 4.5-14x40",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 750,
  },
  {
    id: "leupold-vx3i-4.5-14x50",
    brand: "Leupold",
    model: "VX-3i 4.5-14x50",
    fullName: "Leupold VX-3i 4.5-14x50",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 900,
  },
  {
    id: "leupold-vx3i-6.5-20x50",
    brand: "Leupold",
    model: "VX-3i 6.5-20x50",
    fullName: "Leupold VX-3i 6.5-20x50",
    tubeDiameter: "1in",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },

  // ============================================
  // Leupold VX-Freedom
  // ============================================
  {
    id: "leupold-vx-freedom-1.5-4x20",
    brand: "Leupold",
    model: "VX-Freedom 1.5-4x20",
    fullName: "Leupold VX-Freedom 1.5-4x20",
    tubeDiameter: "1in",
    overallLength: 9.3,
    objectiveDiameter: 20,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "leupold-vx-freedom-2-7x33",
    brand: "Leupold",
    model: "VX-Freedom 2-7x33",
    fullName: "Leupold VX-Freedom 2-7x33",
    tubeDiameter: "1in",
    overallLength: 11.3,
    objectiveDiameter: 33,
    suggestedHeight: "medium",
    msrp: 320,
  },
  {
    id: "leupold-vx-freedom-3-9x40",
    brand: "Leupold",
    model: "VX-Freedom 3-9x40",
    fullName: "Leupold VX-Freedom 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.4,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 350,
  },
  {
    id: "leupold-vx-freedom-3-9x50",
    brand: "Leupold",
    model: "VX-Freedom 3-9x50",
    fullName: "Leupold VX-Freedom 3-9x50",
    tubeDiameter: "1in",
    overallLength: 13.1,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "leupold-vx-freedom-4-12x40",
    brand: "Leupold",
    model: "VX-Freedom 4-12x40",
    fullName: "Leupold VX-Freedom 4-12x40",
    tubeDiameter: "1in",
    overallLength: 12.9,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 400,
  },
];
