import type { ScopeSpec } from "@/types";

export const PRIMARY_ARMS_SCOPES: ScopeSpec[] = [
  {
    id: "primary-arms-glx-2-5-10x44",
    brand: "Primary Arms",
    model: "GLx 2.5-10x44",
    fullName: "Primary Arms GLx 2.5-10x44",
    tubeDiameter: "30mm",
    overallLength: 12.4,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "primary-arms-glx-4-16x50",
    brand: "Primary Arms",
    model: "GLx 4-16x50",
    fullName: "Primary Arms GLx 4-16x50",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 600,
  },
  {
    id: "primary-arms-glx-6-24x50",
    brand: "Primary Arms",
    model: "GLx 6-24x50",
    fullName: "Primary Arms GLx 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.8,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 700,
  },
  {
    id: "primary-arms-slx-1-6x24",
    brand: "Primary Arms",
    model: "SLx 1-6x24",
    fullName: "Primary Arms SLx 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "primary-arms-slx-1-8x24",
    brand: "Primary Arms",
    model: "SLx 1-8x24",
    fullName: "Primary Arms SLx 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.9,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "primary-arms-slx-3-18x50",
    brand: "Primary Arms",
    model: "SLx 3-18x50",
    fullName: "Primary Arms SLx 3-18x50",
    tubeDiameter: "30mm",
    overallLength: 13.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "primary-arms-slx-4-14x44",
    brand: "Primary Arms",
    model: "SLx 4-14x44",
    fullName: "Primary Arms SLx 4-14x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 350,
  },
  {
    id: "primary-arms-plx-1-8x24",
    brand: "Primary Arms",
    model: "PLx 1-8x24",
    fullName: "Primary Arms PLx 1-8x24",
    tubeDiameter: "34mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1100,
  },
  {
    id: "primary-arms-plx-6-30x56",
    brand: "Primary Arms",
    model: "PLx 6-30x56",
    fullName: "Primary Arms PLx 6-30x56",
    tubeDiameter: "34mm",
    overallLength: 15.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1600,
  },
  {
    id: "primary-arms-glx-1-6x24",
    brand: "Primary Arms",
    model: "GLx 1-6x24",
    fullName: "Primary Arms GLx 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 450,
  },
];
