import type { ScopeSpec } from "@/types";

export const RITON_SCOPES: ScopeSpec[] = [
  {
    id: "riton-x7-tactix-1-8x28",
    brand: "Riton",
    model: "X7 Tactix 1-8x28",
    fullName: "Riton X7 Tactix 1-8x28",
    tubeDiameter: "34mm",
    overallLength: 10.5,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 1300,
  },
  {
    id: "riton-x5-tactix-1-6x24",
    brand: "Riton",
    model: "X5 Tactix 1-6x24",
    fullName: "Riton X5 Tactix 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "riton-x3-tactix-3-9x40",
    brand: "Riton",
    model: "X3 Tactix 3-9x40",
    fullName: "Riton X3 Tactix 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 200,
  },
  {
    id: "riton-x7-tactix-3-18x50",
    brand: "Riton",
    model: "X7 Tactix 3-18x50",
    fullName: "Riton X7 Tactix 3-18x50",
    tubeDiameter: "34mm",
    overallLength: 13.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1500,
  },
  {
    id: "riton-x5-tactix-3-15x44",
    brand: "Riton",
    model: "X5 Tactix 3-15x44",
    fullName: "Riton X5 Tactix 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 700,
  },
];
