import type { ScopeSpec } from "@/types";

export const SCHMIDT_BENDER_SCOPES: ScopeSpec[] = [
  {
    id: "schmidt-bender-pm2-3-20x50",
    brand: "Schmidt & Bender",
    model: "PM II 3-20x50",
    fullName: "Schmidt & Bender PM II 3-20x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 4200,
  },
  {
    id: "schmidt-bender-pm2-5-25x56",
    brand: "Schmidt & Bender",
    model: "PM II 5-25x56",
    fullName: "Schmidt & Bender PM II 5-25x56",
    tubeDiameter: "34mm",
    overallLength: 15.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 4500,
  },
  {
    id: "schmidt-bender-pm2-12-50x56",
    brand: "Schmidt & Bender",
    model: "PM II 12-50x56",
    fullName: "Schmidt & Bender PM II 12-50x56",
    tubeDiameter: "34mm",
    overallLength: 16.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 5000,
  },
  {
    id: "schmidt-bender-exos-1-8x24",
    brand: "Schmidt & Bender",
    model: "Exos 1-8x24",
    fullName: "Schmidt & Bender Exos 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 3200,
  },
  {
    id: "schmidt-bender-pm2-1-8x24-shortdot-dual-cc",
    brand: "Schmidt & Bender",
    model: "PM II 1-8x24 ShortDot Dual CC",
    fullName: "Schmidt & Bender PM II 1-8x24 ShortDot Dual CC",
    tubeDiameter: "34mm",
    overallLength: 10.8,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 4000,
  },
  {
    id: "schmidt-bender-pm2-3-27x56",
    brand: "Schmidt & Bender",
    model: "PM II 3-27x56",
    fullName: "Schmidt & Bender PM II 3-27x56",
    tubeDiameter: "34mm",
    overallLength: 16.1,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 5200,
  },
];
