import type { ScopeSpec } from "@/types";

export const SIG_SAUER_SCOPES: ScopeSpec[] = [
  {
    id: "sig-sauer-tango4-1-4x24",
    brand: "Sig Sauer",
    model: "Tango4 1-4x24",
    fullName: "Sig Sauer Tango4 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.0,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "sig-sauer-tango6-1-6x24",
    brand: "Sig Sauer",
    model: "Tango6 1-6x24",
    fullName: "Sig Sauer Tango6 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1600,
  },
  {
    id: "sig-sauer-tango6t-1-6x24",
    brand: "Sig Sauer",
    model: "Tango6T 1-6x24",
    fullName: "Sig Sauer Tango6T 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1900,
  },
  {
    id: "sig-sauer-tango-msr-1-6x24",
    brand: "Sig Sauer",
    model: "Tango-MSR 1-6x24",
    fullName: "Sig Sauer Tango-MSR 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.0,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "sig-sauer-tango-msr-1-8x24",
    brand: "Sig Sauer",
    model: "Tango-MSR 1-8x24",
    fullName: "Sig Sauer Tango-MSR 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 500,
  },
  {
    id: "sig-sauer-tango-msr-lpvo-1-10x28",
    brand: "Sig Sauer",
    model: "Tango-MSR LPVO 1-10x28",
    fullName: "Sig Sauer Tango-MSR LPVO 1-10x28",
    tubeDiameter: "34mm",
    overallLength: 10.9,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 800,
  },
  {
    id: "sig-sauer-tango4-3-12x42",
    brand: "Sig Sauer",
    model: "Tango4 3-12x42",
    fullName: "Sig Sauer Tango4 3-12x42",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "sig-sauer-tango4-4-16x44",
    brand: "Sig Sauer",
    model: "Tango4 4-16x44",
    fullName: "Sig Sauer Tango4 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "sig-sauer-tango4-6-24x50",
    brand: "Sig Sauer",
    model: "Tango4 6-24x50",
    fullName: "Sig Sauer Tango4 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.6,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 900,
  },
  {
    id: "sig-sauer-whiskey5-1-5x20",
    brand: "Sig Sauer",
    model: "Whiskey5 1-5x20",
    fullName: "Sig Sauer Whiskey5 1-5x20",
    tubeDiameter: "1in",
    overallLength: 9.5,
    objectiveDiameter: 20,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "sig-sauer-whiskey5-2-10x42",
    brand: "Sig Sauer",
    model: "Whiskey5 2-10x42",
    fullName: "Sig Sauer Whiskey5 2-10x42",
    tubeDiameter: "30mm",
    overallLength: 12.5,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "sig-sauer-whiskey5-3-15x44",
    brand: "Sig Sauer",
    model: "Whiskey5 3-15x44",
    fullName: "Sig Sauer Whiskey5 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.3,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "sig-sauer-whiskey5-5-25x52",
    brand: "Sig Sauer",
    model: "Whiskey5 5-25x52",
    fullName: "Sig Sauer Whiskey5 5-25x52",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 1000,
  },
  {
    id: "sig-sauer-sierra3-bdx-3-5-10x42",
    brand: "Sig Sauer",
    model: "Sierra3 BDX 3.5-10x42",
    fullName: "Sig Sauer Sierra3 BDX 3.5-10x42",
    tubeDiameter: "30mm",
    overallLength: 12.3,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "sig-sauer-sierra3-bdx-4-5-14x44",
    brand: "Sig Sauer",
    model: "Sierra3 BDX 4.5-14x44",
    fullName: "Sig Sauer Sierra3 BDX 4.5-14x44",
    tubeDiameter: "30mm",
    overallLength: 13.2,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 550,
  },
  {
    id: "sig-sauer-sierra3-bdx-6-5-20x52",
    brand: "Sig Sauer",
    model: "Sierra3 BDX 6.5-20x52",
    fullName: "Sig Sauer Sierra3 BDX 6.5-20x52",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 650,
  },
];
