import type { ScopeSpec } from "@/types";

export const TRIJICON_SCOPES: ScopeSpec[] = [
  {
    id: "trijicon-accupoint-1-4x24",
    brand: "Trijicon",
    model: "AccuPoint 1-4x24",
    fullName: "Trijicon AccuPoint 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1000,
  },
  {
    id: "trijicon-accupoint-2-5-10x56",
    brand: "Trijicon",
    model: "AccuPoint 2.5-10x56",
    fullName: "Trijicon AccuPoint 2.5-10x56",
    tubeDiameter: "30mm",
    overallLength: 13.3,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1300,
  },
  {
    id: "trijicon-accupoint-3-9x40",
    brand: "Trijicon",
    model: "AccuPoint 3-9x40",
    fullName: "Trijicon AccuPoint 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.3,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 1000,
  },
  {
    id: "trijicon-accupoint-5-20x50",
    brand: "Trijicon",
    model: "AccuPoint 5-20x50",
    fullName: "Trijicon AccuPoint 5-20x50",
    tubeDiameter: "30mm",
    overallLength: 13.9,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1400,
  },
  {
    id: "trijicon-credo-1-4x24",
    brand: "Trijicon",
    model: "Credo 1-4x24",
    fullName: "Trijicon Credo 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 900,
  },
  {
    id: "trijicon-credo-1-6x24",
    brand: "Trijicon",
    model: "Credo 1-6x24",
    fullName: "Trijicon Credo 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1100,
  },
  {
    id: "trijicon-credo-1-8x28",
    brand: "Trijicon",
    model: "Credo 1-8x28",
    fullName: "Trijicon Credo 1-8x28",
    tubeDiameter: "34mm",
    overallLength: 10.8,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 1700,
  },
  {
    id: "trijicon-credo-hx-1-6x24",
    brand: "Trijicon",
    model: "Credo HX 1-6x24",
    fullName: "Trijicon Credo HX 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.24,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1400,
  },
  {
    id: "trijicon-tenmile-4-24x50",
    brand: "Trijicon",
    model: "Tenmile 4-24x50",
    fullName: "Trijicon Tenmile 4-24x50",
    tubeDiameter: "30mm",
    overallLength: 13.98,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1500,
  },
  {
    id: "trijicon-tenmile-5-50x56",
    brand: "Trijicon",
    model: "Tenmile 5-50x56",
    fullName: "Trijicon Tenmile 5-50x56",
    tubeDiameter: "34mm",
    overallLength: 16.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2300,
  },
  {
    id: "trijicon-vcog-1-8x28",
    brand: "Trijicon",
    model: "VCOG 1-8x28",
    fullName: "Trijicon VCOG 1-8x28",
    tubeDiameter: "34mm",
    overallLength: 11.0,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 3000,
  },
  {
    id: "trijicon-credo-hx-2-5-15x42",
    brand: "Trijicon",
    model: "Credo HX 2.5-15x42",
    fullName: "Trijicon Credo HX 2.5-15x42",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1600,
  },
  {
    id: "trijicon-tenmile-hx-3-18x44",
    brand: "Trijicon",
    model: "Tenmile HX 3-18x44",
    fullName: "Trijicon Tenmile HX 3-18x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1300,
  },
  {
    id: "trijicon-tenmile-hx-5-25x50",
    brand: "Trijicon",
    model: "Tenmile HX 5-25x50",
    fullName: "Trijicon Tenmile HX 5-25x50",
    tubeDiameter: "30mm",
    overallLength: 14.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1500,
  },
];
