import type { ScopeSpec } from "@/types";

export const VORTEX_SCOPES: ScopeSpec[] = [
  // ============================================
  // Vortex Razor HD Gen III
  // ============================================
  {
    id: "vortex-razor-hd-gen3-1-10x24",
    brand: "Vortex",
    model: "Razor HD Gen III 1-10x24",
    fullName: "Vortex Razor HD Gen III 1-10x24",
    tubeDiameter: "34mm",
    overallLength: 10.1,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2000,
  },
  {
    id: "vortex-razor-hd-gen3-6-36x56",
    brand: "Vortex",
    model: "Razor HD Gen III 6-36x56",
    fullName: "Vortex Razor HD Gen III 6-36x56",
    tubeDiameter: "34mm",
    overallLength: 14.4,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3500,
  },

  // ============================================
  // Vortex Razor HD Gen II
  // ============================================
  {
    id: "vortex-razor-hd-gen2-1-6x24",
    brand: "Vortex",
    model: "Razor HD Gen II 1-6x24",
    fullName: "Vortex Razor HD Gen II 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.1,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1400,
  },
  {
    id: "vortex-razor-hd-gen2-3-18x50",
    brand: "Vortex",
    model: "Razor HD Gen II 3-18x50",
    fullName: "Vortex Razor HD Gen II 3-18x50",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2500,
  },
  {
    id: "vortex-razor-hd-gen2-4.5-27x56",
    brand: "Vortex",
    model: "Razor HD Gen II 4.5-27x56",
    fullName: "Vortex Razor HD Gen II 4.5-27x56",
    tubeDiameter: "34mm",
    overallLength: 14.4,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2800,
  },

  // ============================================
  // Vortex Razor HD LHT (NEW)
  // ============================================
  {
    id: "vortex-razor-hd-lht-1.5-8x32",
    brand: "Vortex",
    model: "Razor HD LHT 1.5-8x32",
    fullName: "Vortex Razor HD LHT 1.5-8x32",
    tubeDiameter: "30mm",
    overallLength: 10.1,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 1300,
  },
  {
    id: "vortex-razor-hd-lht-3-15x42",
    brand: "Vortex",
    model: "Razor HD LHT 3-15x42",
    fullName: "Vortex Razor HD LHT 3-15x42",
    tubeDiameter: "30mm",
    overallLength: 12.1,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1400,
  },
  {
    id: "vortex-razor-hd-lht-3-15x50",
    brand: "Vortex",
    model: "Razor HD LHT 3-15x50",
    fullName: "Vortex Razor HD LHT 3-15x50",
    tubeDiameter: "30mm",
    overallLength: 12.9,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1500,
  },
  {
    id: "vortex-razor-hd-lht-4.5-22x50",
    brand: "Vortex",
    model: "Razor HD LHT 4.5-22x50",
    fullName: "Vortex Razor HD LHT 4.5-22x50",
    tubeDiameter: "30mm",
    overallLength: 14.1,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1600,
  },

  // ============================================
  // Vortex Viper PST Gen II
  // ============================================
  {
    id: "vortex-viper-pst-gen2-1-6x24",
    brand: "Vortex",
    model: "Viper PST Gen II 1-6x24",
    fullName: "Vortex Viper PST Gen II 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 700,
  },
  {
    id: "vortex-viper-pst-gen2-2-10x32",
    brand: "Vortex",
    model: "Viper PST Gen II 2-10x32",
    fullName: "Vortex Viper PST Gen II 2-10x32",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 750,
  },
  {
    id: "vortex-viper-pst-gen2-3-15x44",
    brand: "Vortex",
    model: "Viper PST Gen II 3-15x44",
    fullName: "Vortex Viper PST Gen II 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "vortex-viper-pst-gen2-5-25x50",
    brand: "Vortex",
    model: "Viper PST Gen II 5-25x50",
    fullName: "Vortex Viper PST Gen II 5-25x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },

  // ============================================
  // Vortex Viper HST (NEW)
  // ============================================
  {
    id: "vortex-viper-hst-4-16x44",
    brand: "Vortex",
    model: "Viper HST 4-16x44",
    fullName: "Vortex Viper HST 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "vortex-viper-hst-6-24x50",
    brand: "Vortex",
    model: "Viper HST 6-24x50",
    fullName: "Vortex Viper HST 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 750,
  },

  // ============================================
  // Vortex Strike Eagle
  // ============================================
  {
    id: "vortex-strike-eagle-1-6x24",
    brand: "Vortex",
    model: "Strike Eagle 1-6x24",
    fullName: "Vortex Strike Eagle 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "vortex-strike-eagle-1-8x24",
    brand: "Vortex",
    model: "Strike Eagle 1-8x24",
    fullName: "Vortex Strike Eagle 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "vortex-strike-eagle-3-18x44",
    brand: "Vortex",
    model: "Strike Eagle 3-18x44",
    fullName: "Vortex Strike Eagle 3-18x44",
    tubeDiameter: "30mm",
    overallLength: 13.8,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "vortex-strike-eagle-4-24x50",
    brand: "Vortex",
    model: "Strike Eagle 4-24x50",
    fullName: "Vortex Strike Eagle 4-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "vortex-strike-eagle-5-25x56",
    brand: "Vortex",
    model: "Strike Eagle 5-25x56",
    fullName: "Vortex Strike Eagle 5-25x56",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 600,
  },

  // ============================================
  // Vortex Crossfire II
  // ============================================
  {
    id: "vortex-crossfire2-2-7x32",
    brand: "Vortex",
    model: "Crossfire II 2-7x32",
    fullName: "Vortex Crossfire II 2-7x32",
    tubeDiameter: "1in",
    overallLength: 11.4,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 150,
  },
  {
    id: "vortex-crossfire2-3-9x40",
    brand: "Vortex",
    model: "Crossfire II 3-9x40",
    fullName: "Vortex Crossfire II 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 150,
  },
  {
    id: "vortex-crossfire2-3-9x50",
    brand: "Vortex",
    model: "Crossfire II 3-9x50",
    fullName: "Vortex Crossfire II 3-9x50",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 180,
  },
  {
    id: "vortex-crossfire2-4-12x44",
    brand: "Vortex",
    model: "Crossfire II 4-12x44",
    fullName: "Vortex Crossfire II 4-12x44",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 200,
  },
  {
    id: "vortex-crossfire2-4-12x50",
    brand: "Vortex",
    model: "Crossfire II 4-12x50",
    fullName: "Vortex Crossfire II 4-12x50",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 230,
  },
  {
    id: "vortex-crossfire2-6-18x44",
    brand: "Vortex",
    model: "Crossfire II 6-18x44",
    fullName: "Vortex Crossfire II 6-18x44",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 250,
  },
  {
    id: "vortex-crossfire2-6-24x50",
    brand: "Vortex",
    model: "Crossfire II 6-24x50",
    fullName: "Vortex Crossfire II 6-24x50",
    tubeDiameter: "1in",
    overallLength: 14.6,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 300,
  },

  // ============================================
  // Vortex Diamondback Tactical
  // ============================================
  {
    id: "vortex-diamondback-tactical-4-16x44",
    brand: "Vortex",
    model: "Diamondback Tactical 4-16x44",
    fullName: "Vortex Diamondback Tactical 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "vortex-diamondback-tactical-6-24x50",
    brand: "Vortex",
    model: "Diamondback Tactical 6-24x50",
    fullName: "Vortex Diamondback Tactical 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 450,
  },

  // ============================================
  // Vortex Diamondback HP (NEW)
  // ============================================
  {
    id: "vortex-diamondback-hp-4-16x42",
    brand: "Vortex",
    model: "Diamondback HP 4-16x42",
    fullName: "Vortex Diamondback HP 4-16x42",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 350,
  },
];
