import type { ScopeSpec } from "@/types";

/**
 * Database of popular rifle and crossbow scopes with specifications.
 * Data sourced from manufacturer specifications.
 * 
 * Key measurements:
 * - tubeDiameter: The main tube diameter (1in, 30mm, 34mm, 40mm)
 * - overallLength: Total length in inches (determines guard length)
 * - objectiveDiameter: Objective lens diameter in mm (affects mounting height)
 * - suggestedHeight: Recommended mounting height based on objective size
 */

export const SCOPE_DATABASE: ScopeSpec[] = [
  // ============================================
  // VORTEX OPTICS
  // ============================================
  
  // Vortex Razor HD Gen III
  {
    id: "vortex-razor-hd-gen3-1-10x24",
    brand: "Vortex",
    model: "Razor HD Gen III 1-10x24",
    fullName: "Vortex Razor HD Gen III 1-10x24",
    tubeDiameter: "34mm",
    overallLength: 10.1,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2000,
  },
  {
    id: "vortex-razor-hd-gen3-6-36x56",
    brand: "Vortex",
    model: "Razor HD Gen III 6-36x56",
    fullName: "Vortex Razor HD Gen III 6-36x56",
    tubeDiameter: "34mm",
    overallLength: 14.4,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3500,
  },
  
  // Vortex Razor HD Gen II
  {
    id: "vortex-razor-hd-gen2-1-6x24",
    brand: "Vortex",
    model: "Razor HD Gen II 1-6x24",
    fullName: "Vortex Razor HD Gen II 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.1,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1400,
  },
  {
    id: "vortex-razor-hd-gen2-3-18x50",
    brand: "Vortex",
    model: "Razor HD Gen II 3-18x50",
    fullName: "Vortex Razor HD Gen II 3-18x50",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2500,
  },
  {
    id: "vortex-razor-hd-gen2-4.5-27x56",
    brand: "Vortex",
    model: "Razor HD Gen II 4.5-27x56",
    fullName: "Vortex Razor HD Gen II 4.5-27x56",
    tubeDiameter: "34mm",
    overallLength: 14.4,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2800,
  },
  
  // Vortex Viper PST Gen II
  {
    id: "vortex-viper-pst-gen2-1-6x24",
    brand: "Vortex",
    model: "Viper PST Gen II 1-6x24",
    fullName: "Vortex Viper PST Gen II 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 700,
  },
  {
    id: "vortex-viper-pst-gen2-2-10x32",
    brand: "Vortex",
    model: "Viper PST Gen II 2-10x32",
    fullName: "Vortex Viper PST Gen II 2-10x32",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 750,
  },
  {
    id: "vortex-viper-pst-gen2-3-15x44",
    brand: "Vortex",
    model: "Viper PST Gen II 3-15x44",
    fullName: "Vortex Viper PST Gen II 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "vortex-viper-pst-gen2-5-25x50",
    brand: "Vortex",
    model: "Viper PST Gen II 5-25x50",
    fullName: "Vortex Viper PST Gen II 5-25x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },
  
  // Vortex Strike Eagle
  {
    id: "vortex-strike-eagle-1-6x24",
    brand: "Vortex",
    model: "Strike Eagle 1-6x24",
    fullName: "Vortex Strike Eagle 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "vortex-strike-eagle-1-8x24",
    brand: "Vortex",
    model: "Strike Eagle 1-8x24",
    fullName: "Vortex Strike Eagle 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "vortex-strike-eagle-3-18x44",
    brand: "Vortex",
    model: "Strike Eagle 3-18x44",
    fullName: "Vortex Strike Eagle 3-18x44",
    tubeDiameter: "30mm",
    overallLength: 13.8,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "vortex-strike-eagle-4-24x50",
    brand: "Vortex",
    model: "Strike Eagle 4-24x50",
    fullName: "Vortex Strike Eagle 4-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "vortex-strike-eagle-5-25x56",
    brand: "Vortex",
    model: "Strike Eagle 5-25x56",
    fullName: "Vortex Strike Eagle 5-25x56",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 600,
  },
  
  // Vortex Crossfire II
  {
    id: "vortex-crossfire2-2-7x32",
    brand: "Vortex",
    model: "Crossfire II 2-7x32",
    fullName: "Vortex Crossfire II 2-7x32",
    tubeDiameter: "1in",
    overallLength: 11.4,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 150,
  },
  {
    id: "vortex-crossfire2-3-9x40",
    brand: "Vortex",
    model: "Crossfire II 3-9x40",
    fullName: "Vortex Crossfire II 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 150,
  },
  {
    id: "vortex-crossfire2-3-9x50",
    brand: "Vortex",
    model: "Crossfire II 3-9x50",
    fullName: "Vortex Crossfire II 3-9x50",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 180,
  },
  {
    id: "vortex-crossfire2-4-12x44",
    brand: "Vortex",
    model: "Crossfire II 4-12x44",
    fullName: "Vortex Crossfire II 4-12x44",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 200,
  },
  {
    id: "vortex-crossfire2-4-12x50",
    brand: "Vortex",
    model: "Crossfire II 4-12x50",
    fullName: "Vortex Crossfire II 4-12x50",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 230,
  },
  {
    id: "vortex-crossfire2-6-18x44",
    brand: "Vortex",
    model: "Crossfire II 6-18x44",
    fullName: "Vortex Crossfire II 6-18x44",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 250,
  },
  {
    id: "vortex-crossfire2-6-24x50",
    brand: "Vortex",
    model: "Crossfire II 6-24x50",
    fullName: "Vortex Crossfire II 6-24x50",
    tubeDiameter: "1in",
    overallLength: 14.6,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 300,
  },
  
  // Vortex Diamondback Tactical
  {
    id: "vortex-diamondback-tactical-4-16x44",
    brand: "Vortex",
    model: "Diamondback Tactical 4-16x44",
    fullName: "Vortex Diamondback Tactical 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "vortex-diamondback-tactical-6-24x50",
    brand: "Vortex",
    model: "Diamondback Tactical 6-24x50",
    fullName: "Vortex Diamondback Tactical 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 450,
  },

  // ============================================
  // NIGHTFORCE
  // ============================================
  
  // Nightforce ATACR
  {
    id: "nightforce-atacr-1-8x24",
    brand: "Nightforce",
    model: "ATACR 1-8x24 F1",
    fullName: "Nightforce ATACR 1-8x24 F1",
    tubeDiameter: "34mm",
    overallLength: 10.1,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2800,
  },
  {
    id: "nightforce-atacr-4-16x42",
    brand: "Nightforce",
    model: "ATACR 4-16x42 F1",
    fullName: "Nightforce ATACR 4-16x42 F1",
    tubeDiameter: "34mm",
    overallLength: 12.6,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 2700,
  },
  {
    id: "nightforce-atacr-4-20x50",
    brand: "Nightforce",
    model: "ATACR 4-20x50 F1",
    fullName: "Nightforce ATACR 4-20x50 F1",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 3200,
  },
  {
    id: "nightforce-atacr-5-25x56",
    brand: "Nightforce",
    model: "ATACR 5-25x56 F1",
    fullName: "Nightforce ATACR 5-25x56 F1",
    tubeDiameter: "34mm",
    overallLength: 14.3,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3200,
  },
  {
    id: "nightforce-atacr-7-35x56",
    brand: "Nightforce",
    model: "ATACR 7-35x56 F1",
    fullName: "Nightforce ATACR 7-35x56 F1",
    tubeDiameter: "34mm",
    overallLength: 15.1,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3600,
  },
  
  // Nightforce NX8
  {
    id: "nightforce-nx8-1-8x24",
    brand: "Nightforce",
    model: "NX8 1-8x24 F1",
    fullName: "Nightforce NX8 1-8x24 F1",
    tubeDiameter: "30mm",
    overallLength: 8.75,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1900,
  },
  {
    id: "nightforce-nx8-2.5-20x50",
    brand: "Nightforce",
    model: "NX8 2.5-20x50 F1",
    fullName: "Nightforce NX8 2.5-20x50 F1",
    tubeDiameter: "30mm",
    overallLength: 13.1,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2200,
  },
  {
    id: "nightforce-nx8-4-32x50",
    brand: "Nightforce",
    model: "NX8 4-32x50 F1",
    fullName: "Nightforce NX8 4-32x50 F1",
    tubeDiameter: "30mm",
    overallLength: 13.78,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2400,
  },
  
  // Nightforce SHV
  {
    id: "nightforce-shv-3-10x42",
    brand: "Nightforce",
    model: "SHV 3-10x42",
    fullName: "Nightforce SHV 3-10x42",
    tubeDiameter: "30mm",
    overallLength: 11.9,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1100,
  },
  {
    id: "nightforce-shv-4-14x50",
    brand: "Nightforce",
    model: "SHV 4-14x50 F1",
    fullName: "Nightforce SHV 4-14x50 F1",
    tubeDiameter: "30mm",
    overallLength: 13.2,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1200,
  },
  {
    id: "nightforce-shv-4-14x56",
    brand: "Nightforce",
    model: "SHV 4-14x56",
    fullName: "Nightforce SHV 4-14x56",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1300,
  },
  {
    id: "nightforce-shv-5-20x56",
    brand: "Nightforce",
    model: "SHV 5-20x56",
    fullName: "Nightforce SHV 5-20x56",
    tubeDiameter: "30mm",
    overallLength: 15.2,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1400,
  },

  // ============================================
  // LEUPOLD
  // ============================================
  
  // Leupold Mark 5HD
  {
    id: "leupold-mark5hd-3.6-18x44",
    brand: "Leupold",
    model: "Mark 5HD 3.6-18x44",
    fullName: "Leupold Mark 5HD 3.6-18x44",
    tubeDiameter: "35mm",
    overallLength: 12.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 2500,
  },
  {
    id: "leupold-mark5hd-5-25x56",
    brand: "Leupold",
    model: "Mark 5HD 5-25x56",
    fullName: "Leupold Mark 5HD 5-25x56",
    tubeDiameter: "35mm",
    overallLength: 15.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2800,
  },
  {
    id: "leupold-mark5hd-7-35x56",
    brand: "Leupold",
    model: "Mark 5HD 7-35x56",
    fullName: "Leupold Mark 5HD 7-35x56",
    tubeDiameter: "35mm",
    overallLength: 15.67,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3100,
  },
  
  // Leupold VX-5HD
  {
    id: "leupold-vx5hd-1-5x24",
    brand: "Leupold",
    model: "VX-5HD 1-5x24",
    fullName: "Leupold VX-5HD 1-5x24",
    tubeDiameter: "30mm",
    overallLength: 9.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1100,
  },
  {
    id: "leupold-vx5hd-2-10x42",
    brand: "Leupold",
    model: "VX-5HD 2-10x42",
    fullName: "Leupold VX-5HD 2-10x42",
    tubeDiameter: "30mm",
    overallLength: 12.4,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 1200,
  },
  {
    id: "leupold-vx5hd-3-15x44",
    brand: "Leupold",
    model: "VX-5HD 3-15x44",
    fullName: "Leupold VX-5HD 3-15x44",
    tubeDiameter: "30mm",
    overallLength: 13.1,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1300,
  },
  {
    id: "leupold-vx5hd-3-15x56",
    brand: "Leupold",
    model: "VX-5HD 3-15x56",
    fullName: "Leupold VX-5HD 3-15x56",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1500,
  },
  {
    id: "leupold-vx5hd-4-20x52",
    brand: "Leupold",
    model: "VX-5HD 4-20x52",
    fullName: "Leupold VX-5HD 4-20x52",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 52,
    suggestedHeight: "high",
    msrp: 1700,
  },
  
  // Leupold VX-3i
  {
    id: "leupold-vx3i-1.5-5x20",
    brand: "Leupold",
    model: "VX-3i 1.5-5x20",
    fullName: "Leupold VX-3i 1.5-5x20",
    tubeDiameter: "1in",
    overallLength: 9.3,
    objectiveDiameter: 20,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "leupold-vx3i-2.5-8x36",
    brand: "Leupold",
    model: "VX-3i 2.5-8x36",
    fullName: "Leupold VX-3i 2.5-8x36",
    tubeDiameter: "1in",
    overallLength: 11.3,
    objectiveDiameter: 36,
    suggestedHeight: "medium",
    msrp: 650,
  },
  {
    id: "leupold-vx3i-3.5-10x40",
    brand: "Leupold",
    model: "VX-3i 3.5-10x40",
    fullName: "Leupold VX-3i 3.5-10x40",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 700,
  },
  {
    id: "leupold-vx3i-3.5-10x50",
    brand: "Leupold",
    model: "VX-3i 3.5-10x50",
    fullName: "Leupold VX-3i 3.5-10x50",
    tubeDiameter: "1in",
    overallLength: 12.8,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 800,
  },
  {
    id: "leupold-vx3i-4.5-14x40",
    brand: "Leupold",
    model: "VX-3i 4.5-14x40",
    fullName: "Leupold VX-3i 4.5-14x40",
    tubeDiameter: "1in",
    overallLength: 13.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 750,
  },
  {
    id: "leupold-vx3i-4.5-14x50",
    brand: "Leupold",
    model: "VX-3i 4.5-14x50",
    fullName: "Leupold VX-3i 4.5-14x50",
    tubeDiameter: "1in",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 900,
  },
  {
    id: "leupold-vx3i-6.5-20x50",
    brand: "Leupold",
    model: "VX-3i 6.5-20x50",
    fullName: "Leupold VX-3i 6.5-20x50",
    tubeDiameter: "1in",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },
  
  // Leupold VX-Freedom
  {
    id: "leupold-vx-freedom-1.5-4x20",
    brand: "Leupold",
    model: "VX-Freedom 1.5-4x20",
    fullName: "Leupold VX-Freedom 1.5-4x20",
    tubeDiameter: "1in",
    overallLength: 9.3,
    objectiveDiameter: 20,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "leupold-vx-freedom-2-7x33",
    brand: "Leupold",
    model: "VX-Freedom 2-7x33",
    fullName: "Leupold VX-Freedom 2-7x33",
    tubeDiameter: "1in",
    overallLength: 11.3,
    objectiveDiameter: 33,
    suggestedHeight: "medium",
    msrp: 320,
  },
  {
    id: "leupold-vx-freedom-3-9x40",
    brand: "Leupold",
    model: "VX-Freedom 3-9x40",
    fullName: "Leupold VX-Freedom 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.4,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 350,
  },
  {
    id: "leupold-vx-freedom-3-9x50",
    brand: "Leupold",
    model: "VX-Freedom 3-9x50",
    fullName: "Leupold VX-Freedom 3-9x50",
    tubeDiameter: "1in",
    overallLength: 13.1,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "leupold-vx-freedom-4-12x40",
    brand: "Leupold",
    model: "VX-Freedom 4-12x40",
    fullName: "Leupold VX-Freedom 4-12x40",
    tubeDiameter: "1in",
    overallLength: 12.9,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 400,
  },

  // ============================================
  // SCHMIDT & BENDER
  // ============================================
  {
    id: "schmidt-bender-pm2-3-20x50",
    brand: "Schmidt & Bender",
    model: "PM II 3-20x50",
    fullName: "Schmidt & Bender PM II 3-20x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 4200,
  },
  {
    id: "schmidt-bender-pm2-5-25x56",
    brand: "Schmidt & Bender",
    model: "PM II 5-25x56",
    fullName: "Schmidt & Bender PM II 5-25x56",
    tubeDiameter: "34mm",
    overallLength: 15.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 4500,
  },
  {
    id: "schmidt-bender-pm2-12-50x56",
    brand: "Schmidt & Bender",
    model: "PM II 12-50x56",
    fullName: "Schmidt & Bender PM II 12-50x56",
    tubeDiameter: "34mm",
    overallLength: 16.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 5000,
  },
  {
    id: "schmidt-bender-exos-1-8x24",
    brand: "Schmidt & Bender",
    model: "Exos 1-8x24",
    fullName: "Schmidt & Bender Exos 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 3200,
  },

  // ============================================
  // ZEISS
  // ============================================
  
  // Zeiss Conquest V4
  {
    id: "zeiss-conquest-v4-1-4x24",
    brand: "Zeiss",
    model: "Conquest V4 1-4x24",
    fullName: "Zeiss Conquest V4 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 800,
  },
  {
    id: "zeiss-conquest-v4-3-12x44",
    brand: "Zeiss",
    model: "Conquest V4 3-12x44",
    fullName: "Zeiss Conquest V4 3-12x44",
    tubeDiameter: "30mm",
    overallLength: 13.1,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 900,
  },
  {
    id: "zeiss-conquest-v4-3-12x56",
    brand: "Zeiss",
    model: "Conquest V4 3-12x56",
    fullName: "Zeiss Conquest V4 3-12x56",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1100,
  },
  {
    id: "zeiss-conquest-v4-4-16x44",
    brand: "Zeiss",
    model: "Conquest V4 4-16x44",
    fullName: "Zeiss Conquest V4 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1000,
  },
  {
    id: "zeiss-conquest-v4-6-24x50",
    brand: "Zeiss",
    model: "Conquest V4 6-24x50",
    fullName: "Zeiss Conquest V4 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.7,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1200,
  },
  
  // Zeiss Victory V8
  {
    id: "zeiss-victory-v8-1.1-8x30",
    brand: "Zeiss",
    model: "Victory V8 1.1-8x30",
    fullName: "Zeiss Victory V8 1.1-8x30",
    tubeDiameter: "36mm",
    overallLength: 12.1,
    objectiveDiameter: 30,
    suggestedHeight: "medium",
    msrp: 3500,
  },
  {
    id: "zeiss-victory-v8-1.8-14x50",
    brand: "Zeiss",
    model: "Victory V8 1.8-14x50",
    fullName: "Zeiss Victory V8 1.8-14x50",
    tubeDiameter: "36mm",
    overallLength: 13.6,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 4000,
  },
  {
    id: "zeiss-victory-v8-2.8-20x56",
    brand: "Zeiss",
    model: "Victory V8 2.8-20x56",
    fullName: "Zeiss Victory V8 2.8-20x56",
    tubeDiameter: "36mm",
    overallLength: 14.8,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 4500,
  },

  // ============================================
  // BURRIS
  // ============================================
  {
    id: "burris-xtr2-1-5x24",
    brand: "Burris",
    model: "XTR II 1-5x24",
    fullName: "Burris XTR II 1-5x24",
    tubeDiameter: "34mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 700,
  },
  {
    id: "burris-xtr2-2-10x42",
    brand: "Burris",
    model: "XTR II 2-10x42",
    fullName: "Burris XTR II 2-10x42",
    tubeDiameter: "34mm",
    overallLength: 13.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 800,
  },
  {
    id: "burris-xtr2-3-15x50",
    brand: "Burris",
    model: "XTR II 3-15x50",
    fullName: "Burris XTR II 3-15x50",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 900,
  },
  {
    id: "burris-xtr2-4-20x50",
    brand: "Burris",
    model: "XTR II 4-20x50",
    fullName: "Burris XTR II 4-20x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1000,
  },
  {
    id: "burris-xtr2-5-25x50",
    brand: "Burris",
    model: "XTR II 5-25x50",
    fullName: "Burris XTR II 5-25x50",
    tubeDiameter: "34mm",
    overallLength: 14.75,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1100,
  },
  {
    id: "burris-xtr3-3.3-18x50",
    brand: "Burris",
    model: "XTR III 3.3-18x50",
    fullName: "Burris XTR III 3.3-18x50",
    tubeDiameter: "34mm",
    overallLength: 13.7,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1700,
  },
  {
    id: "burris-xtr3-5.5-30x56",
    brand: "Burris",
    model: "XTR III 5.5-30x56",
    fullName: "Burris XTR III 5.5-30x56",
    tubeDiameter: "34mm",
    overallLength: 14.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1900,
  },
  {
    id: "burris-fullfield-iv-2.5-10x42",
    brand: "Burris",
    model: "Fullfield IV 2.5-10x42",
    fullName: "Burris Fullfield IV 2.5-10x42",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 400,
  },
  {
    id: "burris-fullfield-iv-3-12x42",
    brand: "Burris",
    model: "Fullfield IV 3-12x42",
    fullName: "Burris Fullfield IV 3-12x42",
    tubeDiameter: "1in",
    overallLength: 12.5,
    objectiveDiameter: 42,
    suggestedHeight: "medium",
    msrp: 450,
  },
  {
    id: "burris-fullfield-iv-4-16x50",
    brand: "Burris",
    model: "Fullfield IV 4-16x50",
    fullName: "Burris Fullfield IV 4-16x50",
    tubeDiameter: "1in",
    overallLength: 14.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "burris-fullfield-iv-6-24x50",
    brand: "Burris",
    model: "Fullfield IV 6-24x50",
    fullName: "Burris Fullfield IV 6-24x50",
    tubeDiameter: "1in",
    overallLength: 15.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 550,
  },

  // ============================================
  // PRIMARY ARMS
  // ============================================
  {
    id: "primary-arms-glx-2.5-10x44",
    brand: "Primary Arms",
    model: "GLx 2.5-10x44",
    fullName: "Primary Arms GLx 2.5-10x44",
    tubeDiameter: "30mm",
    overallLength: 12.4,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "primary-arms-glx-4-16x50",
    brand: "Primary Arms",
    model: "GLx 4-16x50",
    fullName: "Primary Arms GLx 4-16x50",
    tubeDiameter: "30mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 600,
  },
  {
    id: "primary-arms-glx-6-24x50",
    brand: "Primary Arms",
    model: "GLx 6-24x50",
    fullName: "Primary Arms GLx 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.8,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 700,
  },
  {
    id: "primary-arms-slx-1-6x24",
    brand: "Primary Arms",
    model: "SLx 1-6x24",
    fullName: "Primary Arms SLx 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "primary-arms-slx-1-8x24",
    brand: "Primary Arms",
    model: "SLx 1-8x24",
    fullName: "Primary Arms SLx 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.9,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "primary-arms-slx-3-18x50",
    brand: "Primary Arms",
    model: "SLx 3-18x50",
    fullName: "Primary Arms SLx 3-18x50",
    tubeDiameter: "30mm",
    overallLength: 13.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "primary-arms-slx-4-14x44",
    brand: "Primary Arms",
    model: "SLx 4-14x44",
    fullName: "Primary Arms SLx 4-14x44",
    tubeDiameter: "30mm",
    overallLength: 13.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 350,
  },

  // ============================================
  // ATHLON OPTICS
  // ============================================
  {
    id: "athlon-argos-btr-gen2-1-8x24",
    brand: "Athlon",
    model: "Argos BTR Gen2 1-8x24",
    fullName: "Athlon Argos BTR Gen2 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 300,
  },
  {
    id: "athlon-argos-btr-gen2-6-24x50",
    brand: "Athlon",
    model: "Argos BTR Gen2 6-24x50",
    fullName: "Athlon Argos BTR Gen2 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.3,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 400,
  },
  {
    id: "athlon-ares-etr-4.5-30x56",
    brand: "Athlon",
    model: "Ares ETR 4.5-30x56",
    fullName: "Athlon Ares ETR 4.5-30x56",
    tubeDiameter: "34mm",
    overallLength: 14.6,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1500,
  },
  {
    id: "athlon-cronus-btr-gen2-4.5-29x56",
    brand: "Athlon",
    model: "Cronus BTR Gen2 4.5-29x56",
    fullName: "Athlon Cronus BTR Gen2 4.5-29x56",
    tubeDiameter: "34mm",
    overallLength: 14.2,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2000,
  },
  {
    id: "athlon-helos-btr-gen2-6-24x56",
    brand: "Athlon",
    model: "Helos BTR Gen2 6-24x56",
    fullName: "Athlon Helos BTR Gen2 6-24x56",
    tubeDiameter: "34mm",
    overallLength: 14.3,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 700,
  },
  {
    id: "athlon-midas-tac-4-16x44",
    brand: "Athlon",
    model: "Midas TAC 4-16x44",
    fullName: "Athlon Midas TAC 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 500,
  },
  {
    id: "athlon-midas-tac-6-24x50",
    brand: "Athlon",
    model: "Midas TAC 6-24x50",
    fullName: "Athlon Midas TAC 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 600,
  },

  // ============================================
  // BUSHNELL
  // ============================================
  {
    id: "bushnell-elite-tactical-xrs2-4.5-30x50",
    brand: "Bushnell",
    model: "Elite Tactical XRS2 4.5-30x50",
    fullName: "Bushnell Elite Tactical XRS2 4.5-30x50",
    tubeDiameter: "34mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1300,
  },
  {
    id: "bushnell-elite-tactical-xrs3-6-36x56",
    brand: "Bushnell",
    model: "Elite Tactical XRS3 6-36x56",
    fullName: "Bushnell Elite Tactical XRS3 6-36x56",
    tubeDiameter: "34mm",
    overallLength: 15.5,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2000,
  },
  {
    id: "bushnell-match-pro-6-24x50",
    brand: "Bushnell",
    model: "Match Pro 6-24x50",
    fullName: "Bushnell Match Pro 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.4,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 500,
  },
  {
    id: "bushnell-engage-2.5-10x44",
    brand: "Bushnell",
    model: "Engage 2.5-10x44",
    fullName: "Bushnell Engage 2.5-10x44",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 250,
  },
  {
    id: "bushnell-engage-4-16x44",
    brand: "Bushnell",
    model: "Engage 4-16x44",
    fullName: "Bushnell Engage 4-16x44",
    tubeDiameter: "30mm",
    overallLength: 13.5,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 300,
  },
  {
    id: "bushnell-engage-6-24x50",
    brand: "Bushnell",
    model: "Engage 6-24x50",
    fullName: "Bushnell Engage 6-24x50",
    tubeDiameter: "30mm",
    overallLength: 14.5,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 350,
  },

  // ============================================
  // TRIJICON
  // ============================================
  {
    id: "trijicon-accupoint-1-4x24",
    brand: "Trijicon",
    model: "AccuPoint 1-4x24",
    fullName: "Trijicon AccuPoint 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.3,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1000,
  },
  {
    id: "trijicon-accupoint-2.5-10x56",
    brand: "Trijicon",
    model: "AccuPoint 2.5-10x56",
    fullName: "Trijicon AccuPoint 2.5-10x56",
    tubeDiameter: "30mm",
    overallLength: 13.3,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1300,
  },
  {
    id: "trijicon-accupoint-3-9x40",
    brand: "Trijicon",
    model: "AccuPoint 3-9x40",
    fullName: "Trijicon AccuPoint 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.3,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 1000,
  },
  {
    id: "trijicon-accupoint-5-20x50",
    brand: "Trijicon",
    model: "AccuPoint 5-20x50",
    fullName: "Trijicon AccuPoint 5-20x50",
    tubeDiameter: "30mm",
    overallLength: 13.9,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1400,
  },
  {
    id: "trijicon-credo-1-4x24",
    brand: "Trijicon",
    model: "Credo 1-4x24",
    fullName: "Trijicon Credo 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 900,
  },
  {
    id: "trijicon-credo-1-6x24",
    brand: "Trijicon",
    model: "Credo 1-6x24",
    fullName: "Trijicon Credo 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1100,
  },
  {
    id: "trijicon-credo-1-8x28",
    brand: "Trijicon",
    model: "Credo 1-8x28",
    fullName: "Trijicon Credo 1-8x28",
    tubeDiameter: "34mm",
    overallLength: 10.8,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 1700,
  },
  {
    id: "trijicon-credo-hx-1-6x24",
    brand: "Trijicon",
    model: "Credo HX 1-6x24",
    fullName: "Trijicon Credo HX 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.24,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1400,
  },
  {
    id: "trijicon-tenmile-4-24x50",
    brand: "Trijicon",
    model: "Tenmile 4-24x50",
    fullName: "Trijicon Tenmile 4-24x50",
    tubeDiameter: "30mm",
    overallLength: 13.98,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 1500,
  },
  {
    id: "trijicon-tenmile-5-50x56",
    brand: "Trijicon",
    model: "Tenmile 5-50x56",
    fullName: "Trijicon Tenmile 5-50x56",
    tubeDiameter: "34mm",
    overallLength: 16.0,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2300,
  },

  // ============================================
  // KAHLES
  // ============================================
  {
    id: "kahles-k16i-1-6x24",
    brand: "Kahles",
    model: "K16i 1-6x24",
    fullName: "Kahles K16i 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.7,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2000,
  },
  {
    id: "kahles-k18i-1-8x24",
    brand: "Kahles",
    model: "K18i 1-8x24",
    fullName: "Kahles K18i 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.9,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2400,
  },
  {
    id: "kahles-k318i-3.5-18x50",
    brand: "Kahles",
    model: "K318i 3.5-18x50",
    fullName: "Kahles K318i 3.5-18x50",
    tubeDiameter: "34mm",
    overallLength: 14.2,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2700,
  },
  {
    id: "kahles-k525i-5-25x56",
    brand: "Kahles",
    model: "K525i 5-25x56",
    fullName: "Kahles K525i 5-25x56",
    tubeDiameter: "34mm",
    overallLength: 15.2,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3300,
  },

  // ============================================
  // SWAROVSKI
  // ============================================
  {
    id: "swarovski-z5-3.5-18x44",
    brand: "Swarovski",
    model: "Z5 3.5-18x44",
    fullName: "Swarovski Z5 3.5-18x44",
    tubeDiameter: "1in",
    overallLength: 14.3,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 1800,
  },
  {
    id: "swarovski-z6-2.5-15x56",
    brand: "Swarovski",
    model: "Z6 2.5-15x56",
    fullName: "Swarovski Z6 2.5-15x56",
    tubeDiameter: "30mm",
    overallLength: 14.2,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 2500,
  },
  {
    id: "swarovski-z8i-1-8x24",
    brand: "Swarovski",
    model: "Z8i 1-8x24",
    fullName: "Swarovski Z8i 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 11.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 2800,
  },
  {
    id: "swarovski-z8i-2.3-18x56",
    brand: "Swarovski",
    model: "Z8i 2.3-18x56",
    fullName: "Swarovski Z8i 2.3-18x56",
    tubeDiameter: "30mm",
    overallLength: 14.6,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3200,
  },
  {
    id: "swarovski-x5i-5-25x56",
    brand: "Swarovski",
    model: "X5i 5-25x56",
    fullName: "Swarovski X5i 5-25x56",
    tubeDiameter: "30mm",
    overallLength: 15.4,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 3500,
  },

  // ============================================
  // CROSSBOW SCOPES
  // ============================================
  {
    id: "vortex-crossfire2-crossbow-2-7x32",
    brand: "Vortex",
    model: "Crossfire II Crossbow 2-7x32",
    fullName: "Vortex Crossfire II Crossbow 2-7x32",
    tubeDiameter: "1in",
    overallLength: 11.4,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 200,
  },
  {
    id: "hawke-xb30-pro-sr-1-5x24",
    brand: "Hawke",
    model: "XB30 Pro SR 1-5x24",
    fullName: "Hawke XB30 Pro SR 1-5x24",
    tubeDiameter: "30mm",
    overallLength: 9.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 250,
  },
  {
    id: "hawke-xb30-pro-sr-1.5-5x32",
    brand: "Hawke",
    model: "XB30 Pro SR 1.5-5x32",
    fullName: "Hawke XB30 Pro SR 1.5-5x32",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 280,
  },
  {
    id: "hawke-xb30-pro-sr-2-7x44",
    brand: "Hawke",
    model: "XB30 Pro SR 2-7x44",
    fullName: "Hawke XB30 Pro SR 2-7x44",
    tubeDiameter: "30mm",
    overallLength: 12.0,
    objectiveDiameter: 44,
    suggestedHeight: "medium",
    msrp: 350,
  },
  {
    id: "killer-instinct-lumix-4x32",
    brand: "Killer Instinct",
    model: "Lumix 4x32",
    fullName: "Killer Instinct Lumix 4x32",
    tubeDiameter: "1in",
    overallLength: 8.5,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 100,
  },
  {
    id: "tenpoint-rangemaster-pro",
    brand: "TenPoint",
    model: "RangeMaster Pro",
    fullName: "TenPoint RangeMaster Pro",
    tubeDiameter: "30mm",
    overallLength: 9.5,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 350,
  },
  {
    id: "barnett-4x32-multi-reticle",
    brand: "Barnett",
    model: "4x32 Multi-Reticle",
    fullName: "Barnett 4x32 Multi-Reticle",
    tubeDiameter: "1in",
    overallLength: 8.0,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 80,
  },
  {
    id: "excalibur-tact-zone-2.5-6x32",
    brand: "Excalibur",
    model: "Tact-Zone 2.5-6x32",
    fullName: "Excalibur Tact-Zone 2.5-6x32",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 32,
    suggestedHeight: "medium",
    msrp: 200,
  },

  // ============================================
  // RITON OPTICS
  // ============================================
  {
    id: "riton-x7-tactix-1-8x28",
    brand: "Riton",
    model: "X7 Tactix 1-8x28",
    fullName: "Riton X7 Tactix 1-8x28",
    tubeDiameter: "34mm",
    overallLength: 10.5,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 1300,
  },
  {
    id: "riton-x5-tactix-1-6x24",
    brand: "Riton",
    model: "X5 Tactix 1-6x24",
    fullName: "Riton X5 Tactix 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.2,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "riton-x3-tactix-3-9x40",
    brand: "Riton",
    model: "X3 Tactix 3-9x40",
    fullName: "Riton X3 Tactix 3-9x40",
    tubeDiameter: "1in",
    overallLength: 12.0,
    objectiveDiameter: 40,
    suggestedHeight: "medium",
    msrp: 200,
  },

  // ============================================
  // MAVEN OPTICS
  // ============================================
  {
    id: "maven-rs.1-1-8x24",
    brand: "Maven",
    model: "RS.1 1-8x24",
    fullName: "Maven RS.1 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.8,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1200,
  },
  {
    id: "maven-rs.4-5-30x56",
    brand: "Maven",
    model: "RS.4 5-30x56",
    fullName: "Maven RS.4 5-30x56",
    tubeDiameter: "34mm",
    overallLength: 14.7,
    objectiveDiameter: 56,
    suggestedHeight: "extra-high",
    msrp: 1600,
  },

  // ============================================
  // STEINER
  // ============================================
  {
    id: "steiner-t6xi-1-6x24",
    brand: "Steiner",
    model: "T6Xi 1-6x24",
    fullName: "Steiner T6Xi 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1600,
  },
  {
    id: "steiner-t6xi-2.5-15x50",
    brand: "Steiner",
    model: "T6Xi 2.5-15x50",
    fullName: "Steiner T6Xi 2.5-15x50",
    tubeDiameter: "34mm",
    overallLength: 14.0,
    objectiveDiameter: 50,
    suggestedHeight: "high",
    msrp: 2400,
  },
  {
    id: "steiner-m8xi-1-8x24",
    brand: "Steiner",
    model: "M8Xi 1-8x24",
    fullName: "Steiner M8Xi 1-8x24",
    tubeDiameter: "34mm",
    overallLength: 10.9,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 3700,
  },

  // ============================================
  // SIG SAUER
  // ============================================
  {
    id: "sig-tango4-1-4x24",
    brand: "Sig Sauer",
    model: "Tango4 1-4x24",
    fullName: "Sig Sauer Tango4 1-4x24",
    tubeDiameter: "30mm",
    overallLength: 10.0,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 600,
  },
  {
    id: "sig-tango6-1-6x24",
    brand: "Sig Sauer",
    model: "Tango6 1-6x24",
    fullName: "Sig Sauer Tango6 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.5,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1600,
  },
  {
    id: "sig-tango6t-1-6x24",
    brand: "Sig Sauer",
    model: "Tango6T 1-6x24",
    fullName: "Sig Sauer Tango6T 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.6,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 1900,
  },
  {
    id: "sig-tango-msr-1-6x24",
    brand: "Sig Sauer",
    model: "Tango-MSR 1-6x24",
    fullName: "Sig Sauer Tango-MSR 1-6x24",
    tubeDiameter: "30mm",
    overallLength: 10.0,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 400,
  },
  {
    id: "sig-tango-msr-1-8x24",
    brand: "Sig Sauer",
    model: "Tango-MSR 1-8x24",
    fullName: "Sig Sauer Tango-MSR 1-8x24",
    tubeDiameter: "30mm",
    overallLength: 10.4,
    objectiveDiameter: 24,
    suggestedHeight: "low",
    msrp: 500,
  },
  {
    id: "sig-tango-msr-lpvo-1-10x28",
    brand: "Sig Sauer",
    model: "Tango-MSR LPVO 1-10x28",
    fullName: "Sig Sauer Tango-MSR LPVO 1-10x28",
    tubeDiameter: "34mm",
    overallLength: 10.9,
    objectiveDiameter: 28,
    suggestedHeight: "low",
    msrp: 800,
  },
];

/**
 * Get all unique brands from the database
 */
export function getScopeBrands(): string[] {
  const brands = new Set(SCOPE_DATABASE.map((scope) => scope.brand));
  return Array.from(brands).sort();
}

/**
 * Search scopes by query string (matches brand or model)
 */
export function searchScopes(query: string): ScopeSpec[] {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  return SCOPE_DATABASE.filter((scope) => {
    const searchText = `${scope.brand} ${scope.model}`.toLowerCase();
    return searchText.includes(normalizedQuery);
  }).slice(0, 20); // Limit results for performance
}

/**
 * Get a scope by its ID
 */
export function getScopeById(id: string): ScopeSpec | undefined {
  return SCOPE_DATABASE.find((scope) => scope.id === id);
}

/**
 * Get scopes by brand
 */
export function getScopesByBrand(brand: string): ScopeSpec[] {
  return SCOPE_DATABASE.filter(
    (scope) => scope.brand.toLowerCase() === brand.toLowerCase()
  );
}
